### ISSUE TITLE
Remote host/DC

### ISSUE THREAD

**Issue by dados** [NickTucker42/ISNDS#1]
Hi!

Does this component support remote host/domain controller. Other than you might be connected to ?

**Comment by NickTucker42** [comment]
By default interactions are "Bindless" meaning that any DC can return data, generally speaking it will be the DC that you have a secure connection with (Login server). For example:: LDAP://CN=aUser,DC=MyDomain,DC=Net

You can also do "Server Binding" if you want to target a specific DC, for example you want to connect to "\\\DC1.mydomain.net"
LDAP://\\\DC1.mydomain.net\CN=aUser,DC=MyDomain,DC=Net

Hope that helps.

**Comment by NickTucker42** [comment]
Please let me know if you have further questions.
